### ISSUE TITLE
Doesn't appear on Webui

### ISSUE THREAD

**Issue by boredafk** [dan4in/PonyHelper#1]
Where is it? Maybe it's because the webui is sd1.5? Running on Sagemaker

**Comment by dan4in** [comment]
**Hello :) i don't know what webui you tried on but it should work on any webui that's based on A1111 can you link what webui you are using 

this extension tested on [Automtic1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui) and [Forge webui](https://github.com/lllyasviel/stable-diffusion-webui-forge)

and if your webui is unsupported like stableswarm...etc you can use [the local standalone version of this tool](https://github.com/dan4in/Stable-diffusion-Prompt-Helper-Pony)**

**Comment by boredafk** [comment]
I use Auto1111
![Screenshot 2024-06-18 015456](https://github.com/dan4in/PonyHelper/assets/170826056/816c5fd0-69aa-4054-bcc8-7b435b12f53b)

**Comment by dan4in** [comment]
I just checked on the extension on A1111 latest Main branch build and Dev SD3 branch and i can't reproduce your problem can you kindly check the file structure if its the cause of the issue that you are facing 


 📁 webui root directory
 ┗━━ 📁 extensions
     ┗━━ 📁 PonyHelper     <----- make sure the name is correct and there's no extra folder like PonyHelper-main/PonyHelper..
         ┗━━ 📁 javascripts
         ┗━━ 📁 scripts
             ┗━━ 📁 Data
                           <----- all files exists 
                           
![image](https://github.com/dan4in/PonyHelper/assets/53431991/30eabbf1-763e-411d-b324-7b76f4784b89)

and you can also try disabling some other extensions to see if its the cause if you still facing the issue after checking the file structure

**Comment by boredafk** [comment]
I got this error 
*** Error loading script: PonyHelper.py
    Traceback (most recent call last):
      File "/home/studio-lab-user/asd/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/studio-lab-user/asd/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/studio-lab-user/asd/extensions/PonyHelper/scripts/PonyHelper.py", line 29, in <module>
        'meta': read_tags_from_file('meta'),
      File "/home/studio-lab-user/asd/extensions/PonyHelper/scripts/PonyHelper.py", line 15, in read_tags_from_file
        raise FileNotFoundError(f"No such file: '{filepath}'")
    FileNotFoundError: No such file: '/home/studio-lab-user/asd/extensions/PonyHelper/scripts/Data/meta'

**Comment by boredafk** [comment]
I got this error
*** Error loading script: PonyHelper.py
Traceback (most recent call last):
File "/home/studio-lab-user/asd/modules/scripts.py", line 508, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "/home/studio-lab-user/asd/modules/script_loading.py", line 13, in load_module
module_spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in _call_with_frames_removed
File "/home/studio-lab-user/asd/extensions/PonyHelper/scripts/PonyHelper.py", line 29, in
'meta': read_tags_from_file('meta'),
File "/home/studio-lab-user/asd/extensions/PonyHelper/scripts/PonyHelper.py", line 15, in read_tags_from_file
raise FileNotFoundError(f"No such file: '{filepath}'")
FileNotFoundError: No such file: '/home/studio-lab-user/asd/extensions/PonyHelper/scripts/Data/meta'

**Comment by boredafk** [comment]
I disabled all extensions except builtin and checked the file

**Comment by dan4in** [comment]
**Hello again thanks for providing me with the error log ^^ now ill be able to solve it i think .. i see the problem related to the script unable to find the data files i updated the script to solve this problem please try downloading the update and trying again to see if it works....♥**
[Fix For No such file: 'filepath Error 2.0.1](https://github.com/dan4in/PonyHelper/commit/b6a8a6f2a48cf6ebdd4cd8f6872f8660a8367f1e)
